---
title: "Revisiting the Wright-Fisher model as a Markov chain"
output: html_notebook
---

We have played with a Wright-Fisher simulator in the exercises for the Monte Carlo
session.  Now, we will return to that, but will use it in tandem with
Monte Carlo to ask questions about the nature of this Markov chain.

Big Note: Even though we are doing Monte Carlo with a Markov chain here, 
this is _not_ Markov chain Monte Carlo.

As before, here is our Wright-Fisher simulation function:
```{r, message=FALSE}
library(tidyverse)
#' simulate R reps of a Wright-Fisher model of size N haploids for T generations from an initial allele count of X0
#'
#' Default values for the simulatiions are given as shown.
#'
#' @param R number of replicate simulations to do
#' @param N number of haploids, each generation, in the population
#' @param T number of generations of sampling to simulate
#' @param X0 the initial number of A alleles.  Must be <= N
WF <- function(
  R = 1000,
  N = 100,
  T = 20,
  X0 = 30
) {
  stopifnot(X0 <= N)
  
  lapply(1:R, function(r) { # cycling over the different replicates
    # initialize a vector to store the results
    x <- rep(NA, T)
    
    # get X1
    x[1] <- rbinom(n = 1, size = N, prob = X0 / N)
    
    # cycle over the remaining generations (for loop is slow but makes
    # it easier to read what is going on)
    for (t in 2:T) {
      x[t] <- rbinom(n = 1, size = N, prob = x[t - 1] / N)
    }
    
    # return a tibble of results
    tibble(
      rep = r,
      t = 1:T,
      x = x
    )
  }) %>%
    bind_rows()   # at the end, bind them all into a single tibble
}
```


## Exercises

For the following exercises we will consider a small population with $N=10$.  

1. Simulate $R = 1000$ replicates of this population,
for $T = 500$ generations, from each of the possible starting
points $X_0 = 0,\ldots,10$.  Use Monte Carlo sampling to approximate
the distribution of states at $T = 500$ for each of the starting
values.
2. Compare the results you obtained for the different starting
values in exercise 1.  Does it appear that there is a single, unique
limiting distribution for this Markov chain? (i.e., so long as you
run it long enough, the probability
of being found in any state is unaffected by where you start).
3. Start at state $X_0=5$ in the chain with $N = 10$, but run only a single
replicate, $R=1$, for $T = 10,000$ generations.  But this time, look
at the distribution of states across the 10,000 time steps
in that single run.  Compare it to the distribution across the $R=1000$
replicates with $X_0 = 5$ of exercise 1. How do they compare?
4. Is the Markov chain made by the Wright-Fisher population ergodic?
5. If not, which of the three conditions---recurrence, aperiodicity, or
irreducibility---is violated?


